const remove = [
	'these tees',
	'hour collection',
	'available for',
	'until they are gone',
	'for one day only',
	'$',
	'gold-plated og coins',
	'Chive Deal',
	'delivery by ',
	'gold coins',
	'Silent Auction',
	'The Chivery tomorrow,',
	'Cyber Monday Deal',
	'% off',
	'yours here',
	'best-selling',
	'coupon code',
	'% on',
	'oz gold',
	'diamond sharpener',
	'Omni DataSafe',
	'compatible with',
	'apple carplay',
	'android auto',
	'free us shipping',
	'win the trip',
	'anniversary of thechive',
	'subscribe here',
	'making your life easier',
	'led light',
	'buy & save',
	'just for you',
	'discount code',
	'Perfect gift',
	'% discount',
	'fraction of the price',
	'new device',
	'migraine',
	'aculief headache relief hat',
	'airphysio',
	'best gift',
	'all prices',
	'sex toy deals',
	'almost caught captain jack sparrow',
	'also available',
	'aquapure',
	'article here',
	'ios apps',
	'return policy',
	'available here',
	'bottles of wine',
	'available now',
	'ball marker',
	'heck it out',
	'kratom',
	'bargains',
	'best selling',
	'cbd',
	'big sale',
	'black friday',
	'black snake gold',
	'brand new collection',
	'bundle',
	'but i wouldn’t click it if i were you. nothing to see here',
	'buy from',
	'buy one, get one free',
	'change another life together',
	'charging station',
	'relieve pain ',
	'chive charities',
	'chive it event',
	'chive tees',
	'chive tv',
	'chive50',
	'chivers $ave',
	'click here',
	'only savings',
	'claim your free',
	'code kcco',
	'collection now',
	'come out today',
	'copper farley',
	'cupstation',
	'cxse',
	'deals here',
	'dodow',
	'donate here',
	'donate to chive',
	'duromax',
	'ed meds',
	'enjoy the summer',
	'enjoy these new designs',
	'enter now',
	'entire collection',
	'every month',
	'exclusive code',
	'exclusive deal',
	'experience it for yourself',
	'eyeque',
	'fittrack',
	'fixd',
	'flexsafe',
	'float on',
	'floor lamp',
	'for free',
	'for only $',
	'for the price of',
	'foreverpen',
	'free shipping',
	'from the chivery',
	'get it here',
	'money',
	'save you',
	'sold!',
	'get your',
	'chivers save',
	'save on',
	'get it while you can',
	'get yours',
	'giveaway',
	'giving away',
	'gofundme',
	'golf balls',
	'green lumber',
	'handheld gaming console',
	'head to peachwood and get these toys on sale now!',
	'help us show support',
	'here now',
	'he’s the captain now',
	'his name was simon',
	'hoodies',
	'hulu',
	'ichive',
	'instagram post',
	'jem glass',
	'limited chive',
	'limited time',
	'loud noises',
	'mantra labs',
	'maskfone',
	'microsoft office',
	'my happy feet',
	'nasa scientists created',
	'neck hammock',
	'new collection',
	'new gear here!',
	'olumiring',
	'on sale',
	'only available',
	'orders',
	'peachwood',
	'playstation plus',
	'pre-order',
	'premium',
	'products and more!',
	'promo code',
	'quit smoking',
	'read more about this',
	'redeem',
	'reveille bridge veterans foundation',
	'right here',
	'saber battery',
	'safari login issues',
	'save big',
	'save up',
	'chive only deal',
	'shop black snake gold',
	'show support for ukraine here.',
	'sign up for',
	'sign up',
	'rsvp',
	'lifetime membership',
	'sign-up',
	'signing up',
	'silver caddy shack ap coins!',
	'sore neck',
	'spaceballs tee',
	't-shirts here',
	'tee right here',
	'chive savings',
	'the kitchen cube',
	'the wand',
	'thechive box',
	'thechive membership',
	'thechivery',
	'thephotostickmobile',
	'theraice',
	'this beautifully designed, space-saving lamp',
	'to save',
	'use code',
	'use promo',
	'verified@thechive.com',
	'while supplies last',
	'while supply',
	'with code',
	'wordpress rep',
	'youtube',
	'live forever golf',
	'zero fg',
]